language:
  - swift
osx_image: xcode10.1

cache:
  - bundler
  - cocoapods

env:
  global:
    - WORKSPACE="SearchAppstore.xcworkspace"
    - IOS_SDK="iphonesimulator12.1"
    - IOS_DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.1"
    - SCHEME="SearchAppstore"
#  matrix:
#    - SCHEME="SearchAppstore"        SDK="$IOS_SDK"      ACTION="test"

install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install

script:
  - set -o pipefail && xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$IOS_DESTINATION" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
